name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build

      - name: Verificar archivos generados
        run: ls -l ./site

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./site

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
